# Generated by Django 4.1.1 on 2022-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p',
            name='sc',
            field=models.BooleanField(default=False, verbose_name='Confirmed Registration?'),
        ),
    ]
