# Generated by Django 4.1.1 on 2022-09-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('u', '0002_alter_p_sc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p', to=settings.AUTH_USER_MODEL),
        ),
    ]
