# Generated by Django 4.1.1 on 2022-09-19 18:21

from django.db import migrations, models
import u.models


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0003_alter_p_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='p',
            name='a',
            field=models.ImageField(default='d/a.jpg', upload_to=u.models.ua, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='p',
            name='b',
            field=models.ImageField(blank=True, null=True, upload_to=u.models.ub, verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='p',
            name='n',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
    ]
