# Generated by Django 4.1.1 on 2022-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0004_p_a_p_b_p_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='p',
            name='p',
            field=models.CharField(choices=[('1', 'Public'), ('0', 'Public to followers'), ('-1', 'Private')], default='1', max_length=19),
        ),
    ]
