# Generated by Django 4.1.1 on 2022-09-21 09:58

from django.db import migrations, models
import u.models


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0005_p_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p',
            name='b',
            field=models.ImageField(default='uploads/u/p/b/function_uuid4_at_0x000001F1F92D96C0.jpeg', upload_to=u.models.ub, verbose_name='Banner'),
        ),
    ]
