# Generated by Django 4.1.1 on 2022-09-21 21:09

from django.db import migrations, models
import django.db.models.deletion
import u.models


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0006_alter_p_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.ImageField(upload_to=u.models.ub)),
                ('ca', models.DateTimeField(auto_now_add=True)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bc', to='u.p')),
            ],
            options={
                'ordering': ['ca'],
            },
        ),
        migrations.AlterField(
            model_name='p',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='u.b'),
        ),
    ]
