# Generated by Django 4.1.1 on 2022-09-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0007_b_alter_p_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p',
            name='b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='u.b'),
        ),
    ]
