# Generated by Django 4.1.1 on 2022-09-21 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('u', '0008_alter_p_b'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b',
            options={'ordering': ['ca'], 'verbose_name': 'Banner'},
        ),
        migrations.AlterField(
            model_name='b',
            name='u',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bc', to=settings.AUTH_USER_MODEL),
        ),
    ]
