# Generated by Django 4.1.1 on 2022-09-21 22:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0009_alter_b_options_alter_b_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='b',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='p',
            name='b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pb', to='u.b'),
        ),
    ]
