# Generated by Django 4.1.1 on 2022-09-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0010_b_uid_alter_p_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.DateTimeField(auto_now_add=True, verbose_name='Followed At')),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profile', to='u.p', verbose_name='Follower')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u.p', verbose_name='Followed Profile')),
            ],
            options={
                'verbose_name': 'Follower',
                'ordering': ['-fa'],
            },
        ),
    ]
