# Generated by Django 4.1.1 on 2022-09-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0012_alter_f_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f',
            old_name='p',
            new_name='pr',
        ),
    ]
