# Generated by Django 4.1.1 on 2022-09-19 11:13

import d.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('d', models.TextField(blank=True, max_length=999, null=True, verbose_name='Description')),
                ('c', models.FileField(blank=True, null=True, upload_to=d.models.uc, verbose_name='Cover')),
                ('ca', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ua', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
                'ordering': ['ua'],
            },
        ),
        migrations.CreateModel(
            name='DE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('c', models.TextField(blank=True, max_length=999, null=True, verbose_name='Content')),
                ('cr', models.CharField(choices=[('#aaa', 'Black'), ('#fff', 'White')], max_length=10, verbose_name='Color')),
                ('b', models.FileField(blank=True, null=True, upload_to=d.models.uc, verbose_name='Background')),
                ('ca', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ua', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Diary Entry',
                'verbose_name_plural': 'Diary Entries',
                'ordering': ['ua'],
            },
        ),
        migrations.CreateModel(
            name='F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(blank=True, null=True, upload_to=d.models.uf, verbose_name='File')),
                ('aa', models.DateTimeField(auto_now=True, verbose_name='Added At')),
                ('e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.de', verbose_name='Diary Entry')),
            ],
            options={
                'verbose_name': 'File',
                'ordering': ['aa'],
            },
        ),
    ]
