# Generated by Django 4.1.1 on 2022-09-19 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='de',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
