# Generated by Django 4.1.1 on 2022-09-19 12:22

import d.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0003_alter_p_u'),
        ('d', '0002_de_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='de',
            name='a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='u.p'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='f',
            name='aa',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='f',
            name='f',
            field=models.FileField(default='s', upload_to=d.models.uf, verbose_name='File'),
            preserve_default=False,
        ),
    ]
