# Generated by Django 4.1.1 on 2022-09-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0004_d_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d',
            old_name='p',
            new_name='a',
        ),
    ]
