# Generated by Django 4.1.1 on 2022-09-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0007_re'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='re',
            options={'ordering': ['-ca'], 'verbose_name': 'Reposted Diary', 'verbose_name_plural': 'Reposted Diaries'},
        ),
        migrations.RenameField(
            model_name='re',
            old_name='p',
            new_name='a',
        ),
    ]
