# Generated by Django 4.1.1 on 2022-09-22 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0008_alter_re_options_rename_p_re_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='re',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
