# Generated by Django 4.1.1 on 2022-09-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0009_re_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='re',
            name='t',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='re',
            name='de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposted_post', to='d.de'),
        ),
    ]
