# Generated by Django 4.1.1 on 2022-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0010_re_t_alter_re_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='de',
            name='v',
            field=models.PositiveIntegerField(default=0, verbose_name='Entry views'),
        ),
        migrations.AddField(
            model_name='re',
            name='v',
            field=models.PositiveIntegerField(default=0, verbose_name='Entry views'),
        ),
        migrations.AlterField(
            model_name='re',
            name='t',
            field=models.CharField(blank=True, max_length=333, null=True, verbose_name='Text'),
        ),
    ]
