# Generated by Django 4.1.1 on 2022-09-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0014_rename_pr_f_p'),
        ('d', '0011_de_v_re_v_alter_re_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='RL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la', models.DateTimeField(auto_now_add=True, verbose_name='Liked At')),
                ('e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.de', verbose_name='Diary Entry')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u.p', verbose_name='Liking Profile')),
            ],
            options={
                'verbose_name': 'Like',
                'ordering': ['la'],
            },
        ),
        migrations.CreateModel(
            name='EL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la', models.DateTimeField(auto_now_add=True, verbose_name='Liked At')),
                ('e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.de', verbose_name='Diary Entry')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u.p', verbose_name='Liking Profile')),
            ],
            options={
                'verbose_name': 'Like',
                'ordering': ['la'],
            },
        ),
        migrations.AddField(
            model_name='de',
            name='l',
            field=models.ManyToManyField(blank=True, null=True, to='d.el'),
        ),
        migrations.AddField(
            model_name='re',
            name='l',
            field=models.ManyToManyField(blank=True, null=True, to='d.rl'),
        ),
    ]
