# Generated by Django 4.1.1 on 2022-09-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0013_alter_el_options_alter_rl_options_de_h_re_h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='de',
            name='cr',
        ),
    ]
